### ISSUE TITLE
Add config vars to support cgroup v2

### ISSUE THREAD

**Issue by hbrls** [hashicorp/packer-plugin-alicloud#139] opened 2024-04-20 03:20 UTC
#### Description

Installing k3s with packer will fail, with the error message `failed to find cpu cgroup (v2)`.

Need some config vars like:

https://github.com/AliyunContainerService/ack-image-builder/blob/master/scripts/set-cgroupv2.sh

https://help.aliyun.com/zh/ack/ack-managed-and-ack-dedicated/user-guide/create-cgroup-v2-nodes-from-a-custom-image

#### Use Case(s)

Any relevant use-cases that you see.

#### Potential configuration

```
```

**Comment by hbrls** [comment] 2024-05-16 03:18
After some document research, I think `Alicloud` do support v2.
But it uses v2 to start a real ec2, *vs.* it uses v1 to start a packer build image process.

And I suppose the [line](https://github.com/AliyunContainerService/ack-image-builder/blob/master/scripts/set-cgroupv2.sh#L6) can **indicate** Alicloud to use v2 also when packer build.

I've no knowledge about the base implement.

**Comment by lbajolet-hashicorp** [comment] 2024-05-16 13:31
Hey @hbrls,

It's a system setting, the line you're referring to updates the boot parameters for the kernel so it enables cgroupsv2. This is OS-specific, not something Packer or this plugin can or should (imo) set, this requires access to the filesystem, we're outside the boundaries of what the builder can do here.

My advice if you need cgroupsv2 is to use the script provided by alicloud (if relevant), or refer to documentation to know which command to invoke/setting to enable in a shell script provisioner to run in the instance you're building the image from.

With this said, I don't think there's something to do on the Packer front, so I'll close this issue as this is not a bug, nor something that falls in the plugin's responsibility, but please feel free to reopen if there's something I'm missing.

Thanks!

**Closed by lbajolet-hashicorp** 2024-05-16 13:31 UTC
Labels: enhancement, stage/needs-discussion
